### ISSUE TITLE
[Bug] CsoundQt rev 969 [sf#101]

### ISSUE THREAD

**Issue by mantaraya36** [mantaraya36/CsoundQt#101]
**Reported by *anonymous on 2012-02-18 08:27 UTC**
Try to compile on Ubuntu 10.04, I got this error

src/qutecsound.cpp:161: error: ‘closeTabButton’ was not declared in this scope

**Comment by mantaraya36** [comment]
**Updated by mantaraya36 on 2012-02-23 14:20 UTC**
- **status**: open --> open-fixed

**Comment by mantaraya36** [comment]
**Updated by mantaraya36 on 2012-02-23 14:21 UTC**
- **status**: open-fixed --> closed-fixed
